- name: install prerequisitet cron
  apt:
    name:
      - cron

- name: enable service cron and start it
  ansible.builtin.systemd_service:
    name: cron
    daemon_reload: true
    state: started


